AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

#
# Lint
#

Lint/HandleExceptions:
  Enabled: false

Lint/Loop:
  Enabled: false

#
# Metrics
#

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 128

Metrics/ClassLength:
  Max: 128

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  CountComments: false
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

#
# Performance
#

Performance/RegexpMatch:
  Enabled: false

#
# Style
#

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/GlobalVars:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false
