language: ruby
sudo: false
cache: bundler

bundler_args: --without development

branches:
  only:
    - master

os:
  - linux
  - osx

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - ruby-head
  - jruby-9.1.5.0 # latest stable
  - jruby-head
  - rbx

env:
  global:
    - JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M"      
  matrix:
    - NIO4R_PURE=false
    - NIO4R_PURE=true

matrix:
  fast_finish: true
  allow_failures:
    - os:  osx # TODO: make tests pass reliably on OS X
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
    - rvm: jruby-1.7
      env: NIO4R_PURE=true
    - rvm: jruby-9.1
      env: NIO4R_PURE=true

notifications:
  irc: "irc.freenode.org#celluloid"
