language: ruby
sudo: false
cache: bundler
branches:
  only:
    - master

bundler_args: --without development

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - ruby-head
  - jruby-1.7
  - jruby-9.0.5.0 # latest travis-ci preinstalled version
  - jruby-head
  - rbx

env:
  - NIO4R_PURE=false
  - NIO4R_PURE=true

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
    - rvm: jruby-1.7
      env: NIO4R_PURE=true
    - rvm: jruby-9.1
      env: NIO4R_PURE=true

notifications:
  irc: "irc.freenode.org#celluloid"
