language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.1.1
  - 2.2.2
  - 2.3.0
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2

env:
  - NIO4R_PURE=false
  - NIO4R_PURE=true

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: jruby
      env: NIO4R_PURE=true

notifications:
  irc: "irc.freenode.org#celluloid"
