language: ruby
sudo: false
cache: bundler

before_install:
  - gem update --system 2.6.10
  - gem --version

bundler_args: --without development

branches:
  only:
    - master

rvm:
  - jruby-9.1.8.0 # latest stable
  - 2.2.7
  - 2.3.4
  - 2.4.1

env:
  global:
    - JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M"      
  matrix:
    - NIO4R_PURE=false
    - NIO4R_PURE=true

matrix:
  fast_finish: true

notifications:
  irc: "irc.freenode.org#celluloid"
